/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppointNitramRouteImport } from './routes/appoint-nitram'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackRouteImport } from './routes/track'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ApiSendAssessmentRouteImport } from './routes/api/send-assessment'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as QuoteCustomsClearanceRouteImport } from './routes/quote_.customs-clearance'
import { Route as QuoteFreightQuotationRouteImport } from './routes/quote_.freight-quotation'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminCustomersIdRouteImport } from './routes/admin/customers/$id'
import { Route as AdminDocumentsIndexRouteImport } from './routes/admin/documents/index'
import { Route as AdminLeadsIndexRouteImport } from './routes/admin/leads/index'
import { Route as AdminLeadsIdRouteImport } from './routes/admin/leads/$id'
import { Route as AdminQuotesIndexRouteImport } from './routes/admin/quotes/index'
import { Route as AdminQuotesIdRouteImport } from './routes/admin/quotes/$id'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminShipmentsIndexRouteImport } from './routes/admin/shipments/index'
import { Route as AdminShipmentsIdRouteImport } from './routes/admin/shipments/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointNitramRoute = AppointNitramRouteImport.update({
  id: '/appoint-nitram',
  path: '/appoint-nitram',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendAssessmentRoute = ApiSendAssessmentRouteImport.update({
  id: '/api/send-assessment',
  path: '/api/send-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteCustomsClearanceRoute = QuoteCustomsClearanceRouteImport.update({
  id: '/quote_/customs-clearance',
  path: '/quote/customs-clearance',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteFreightQuotationRoute = QuoteFreightQuotationRouteImport.update({
  id: '/quote_/freight-quotation',
  path: '/quote/freight-quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/admin/customers/',
  path: '/admin/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/admin/customers/$id',
  path: '/admin/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsIndexRoute = AdminDocumentsIndexRouteImport.update({
  id: '/admin/documents/',
  path: '/admin/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: '/admin/leads/',
  path: '/admin/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsIdRoute = AdminLeadsIdRouteImport.update({
  id: '/admin/leads/$id',
  path: '/admin/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuotesIndexRoute = AdminQuotesIndexRouteImport.update({
  id: '/admin/quotes/',
  path: '/admin/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuotesIdRoute = AdminQuotesIdRouteImport.update({
  id: '/admin/quotes/$id',
  path: '/admin/quotes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShipmentsIndexRoute = AdminShipmentsIndexRouteImport.update({
  id: '/admin/shipments/',
  path: '/admin/shipments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShipmentsIdRoute = AdminShipmentsIdRouteImport.update({
  id: '/admin/shipments/$id',
  path: '/admin/shipments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appoint-nitram': typeof AppointNitramRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/api/send-assessment': typeof ApiSendAssessmentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/quote/customs-clearance': typeof QuoteCustomsClearanceRoute
  '/quote/freight-quotation': typeof QuoteFreightQuotationRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/quotes/$id': typeof AdminQuotesIdRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/documents/': typeof AdminDocumentsIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/admin/quotes/': typeof AdminQuotesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/shipments/': typeof AdminShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appoint-nitram': typeof AppointNitramRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/api/send-assessment': typeof ApiSendAssessmentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/quote/customs-clearance': typeof QuoteCustomsClearanceRoute
  '/quote/freight-quotation': typeof QuoteFreightQuotationRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/quotes/$id': typeof AdminQuotesIdRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/documents': typeof AdminDocumentsIndexRoute
  '/admin/leads': typeof AdminLeadsIndexRoute
  '/admin/quotes': typeof AdminQuotesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/shipments': typeof AdminShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appoint-nitram': typeof AppointNitramRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/api/send-assessment': typeof ApiSendAssessmentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/quote_/customs-clearance': typeof QuoteCustomsClearanceRoute
  '/quote_/freight-quotation': typeof QuoteFreightQuotationRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/quotes/$id': typeof AdminQuotesIdRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/documents/': typeof AdminDocumentsIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/admin/quotes/': typeof AdminQuotesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/shipments/': typeof AdminShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appoint-nitram'
    | '/assessment'
    | '/contact'
    | '/documents'
    | '/forgot-password'
    | '/industries'
    | '/leadership'
    | '/login'
    | '/privacy'
    | '/quote'
    | '/resources'
    | '/services'
    | '/terms'
    | '/track'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/api/send-assessment'
    | '/blog/$slug'
    | '/quote/customs-clearance'
    | '/quote/freight-quotation'
    | '/admin/'
    | '/blog/'
    | '/admin/customers/$id'
    | '/admin/leads/$id'
    | '/admin/quotes/$id'
    | '/admin/shipments/$id'
    | '/admin/blog/'
    | '/admin/customers/'
    | '/admin/documents/'
    | '/admin/leads/'
    | '/admin/quotes/'
    | '/admin/settings/'
    | '/admin/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appoint-nitram'
    | '/assessment'
    | '/contact'
    | '/documents'
    | '/forgot-password'
    | '/industries'
    | '/leadership'
    | '/login'
    | '/privacy'
    | '/quote'
    | '/resources'
    | '/services'
    | '/terms'
    | '/track'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/api/send-assessment'
    | '/blog/$slug'
    | '/quote/customs-clearance'
    | '/quote/freight-quotation'
    | '/admin'
    | '/blog'
    | '/admin/customers/$id'
    | '/admin/leads/$id'
    | '/admin/quotes/$id'
    | '/admin/shipments/$id'
    | '/admin/blog'
    | '/admin/customers'
    | '/admin/documents'
    | '/admin/leads'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/shipments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appoint-nitram'
    | '/assessment'
    | '/contact'
    | '/documents'
    | '/forgot-password'
    | '/industries'
    | '/leadership'
    | '/login'
    | '/privacy'
    | '/quote'
    | '/resources'
    | '/services'
    | '/terms'
    | '/track'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/api/send-assessment'
    | '/blog/$slug'
    | '/quote_/customs-clearance'
    | '/quote_/freight-quotation'
    | '/admin/'
    | '/blog/'
    | '/admin/customers/$id'
    | '/admin/leads/$id'
    | '/admin/quotes/$id'
    | '/admin/shipments/$id'
    | '/admin/blog/'
    | '/admin/customers/'
    | '/admin/documents/'
    | '/admin/leads/'
    | '/admin/quotes/'
    | '/admin/settings/'
    | '/admin/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointNitramRoute: typeof AppointNitramRoute
  AssessmentRoute: typeof AssessmentRoute
  ContactRoute: typeof ContactRoute
  DocumentsRoute: typeof DocumentsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IndustriesRoute: typeof IndustriesRoute
  LeadershipRoute: typeof LeadershipRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  ApiSendAssessmentRoute: typeof ApiSendAssessmentRoute
  BlogSlugRoute: typeof BlogSlugRoute
  QuoteCustomsClearanceRoute: typeof QuoteCustomsClearanceRoute
  QuoteFreightQuotationRoute: typeof QuoteFreightQuotationRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminLeadsIdRoute: typeof AdminLeadsIdRoute
  AdminQuotesIdRoute: typeof AdminQuotesIdRoute
  AdminShipmentsIdRoute: typeof AdminShipmentsIdRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminDocumentsIndexRoute: typeof AdminDocumentsIndexRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
  AdminQuotesIndexRoute: typeof AdminQuotesIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminShipmentsIndexRoute: typeof AdminShipmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appoint-nitram': {
      id: '/appoint-nitram'
      path: '/appoint-nitram'
      fullPath: '/appoint-nitram'
      preLoaderRoute: typeof AppointNitramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-assessment': {
      id: '/api/send-assessment'
      path: '/api/send-assessment'
      fullPath: '/api/send-assessment'
      preLoaderRoute: typeof ApiSendAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote_/customs-clearance': {
      id: '/quote_/customs-clearance'
      path: '/quote/customs-clearance'
      fullPath: '/quote/customs-clearance'
      preLoaderRoute: typeof QuoteCustomsClearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote_/freight-quotation': {
      id: '/quote_/freight-quotation'
      path: '/quote/freight-quotation'
      fullPath: '/quote/freight-quotation'
      preLoaderRoute: typeof QuoteFreightQuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/admin/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents/': {
      id: '/admin/documents/'
      path: '/admin/documents'
      fullPath: '/admin/documents/'
      preLoaderRoute: typeof AdminDocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads/': {
      id: '/admin/leads/'
      path: '/admin/leads'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads/$id': {
      id: '/admin/leads/$id'
      path: '/admin/leads/$id'
      fullPath: '/admin/leads/$id'
      preLoaderRoute: typeof AdminLeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quotes/': {
      id: '/admin/quotes/'
      path: '/admin/quotes'
      fullPath: '/admin/quotes/'
      preLoaderRoute: typeof AdminQuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quotes/$id': {
      id: '/admin/quotes/$id'
      path: '/admin/quotes/$id'
      fullPath: '/admin/quotes/$id'
      preLoaderRoute: typeof AdminQuotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipments/': {
      id: '/admin/shipments/'
      path: '/admin/shipments'
      fullPath: '/admin/shipments/'
      preLoaderRoute: typeof AdminShipmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipments/$id': {
      id: '/admin/shipments/$id'
      path: '/admin/shipments/$id'
      fullPath: '/admin/shipments/$id'
      preLoaderRoute: typeof AdminShipmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointNitramRoute: AppointNitramRoute,
  AssessmentRoute: AssessmentRoute,
  ContactRoute: ContactRoute,
  DocumentsRoute: DocumentsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IndustriesRoute: IndustriesRoute,
  LeadershipRoute: LeadershipRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  ApiSendAssessmentRoute: ApiSendAssessmentRoute,
  BlogSlugRoute: BlogSlugRoute,
  QuoteCustomsClearanceRoute: QuoteCustomsClearanceRoute,
  QuoteFreightQuotationRoute: QuoteFreightQuotationRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminLeadsIdRoute: AdminLeadsIdRoute,
  AdminQuotesIdRoute: AdminQuotesIdRoute,
  AdminShipmentsIdRoute: AdminShipmentsIdRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminDocumentsIndexRoute: AdminDocumentsIndexRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
  AdminQuotesIndexRoute: AdminQuotesIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminShipmentsIndexRoute: AdminShipmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
